using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace sandcastle_html_sitemap_gen
{
    public class SitemapGenFromURLs
    {
        private List<string> XML;

        private double _priority = 0.5;

        public SitemapGenFromURLs()
        {
            XML = new List<string>();
        }

        public string[] Generate(string[] urls, double priority = 0.5)
        {
            _priority = priority;

            AddHeader();

            foreach (var url in urls)
            {
                AddItem(url);
            }

            AddFooter();

            return XML.ToArray();
        }

        private void AddItem(string url)
        {
            XML.Add("<url>");
            XML.Add("<loc>" + url + "</loc>");

            string date = DateTime.Now.ToString("yyyy-MM-dd") + "T" + DateTime.Now.ToString("HH:mm:ss") + "+00:00";
            XML.Add("<lastmod>" + date + "</lastmod>");
            //	2018-07-28T23:36:21+00:00
            XML.Add("<changefreq>weekly</changefreq>");
            XML.Add("<priority>" + _priority.ToString("F2").Replace(",", ".") + "</priority>");
            XML.Add("</url>");
        }

        private void AddHeader()
        {
            XML.Add("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
            XML.Add("<!-- Sitemap File Generated by https://github.com/roman-minyaylov/SandcastleHTMLSitemapGen at" + DateTime.Now.ToString("yyyy-MM-dd") + " -->");

            XML.Add("<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\"");
            XML.Add("xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"");
            XML.Add("xsi:schemaLocation=\"http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd\" >");
        }

        private void AddFooter()
        {
            XML.Add("</urlset>");
        }
    }
}
